spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
  jpa:
    open-in-view: true

server:
  servlet:
    session:
      persistent: false
      cookie:
        secure: false
        http-only: true
        same-site: lax